### ISSUE TITLE
Add support for .sma (amxx) files

### ISSUE THREAD

**Issue by xPaw** [50Wliu/language-sourcepawn#2]
This guy forked your repository to add amxx support, but there's no real reason for it to be a separate package: https://forums.alliedmods.net/showthread.php?t=262349

Should be as simple as adding an alias for `.sma` -> `.sp`

**Comment by winstliu** [comment]
Agreed, a pretty simple change: https://github.com/50Wliu/language-sourcepawn/blob/master/grammars/sourcepawn.cson#L3-L6

Just curious though, what's the main differences between AMXX and SM?  If there's more than a few I could add a separate .cson file for it and change the scope name, etc (like [language-c](https://github.com/atom/language-c/tree/master/grammars) does).

**Comment by xPaw** [comment]
It should work fine without any changes.

**Comment by WildCard65** [comment]
@50Wliu I believe(not 100% sure) Sourcepawn evolved from AMXX's Pawn(my reasoning is from SourcePawn has commit messages/stuff that are AMXX based).  
Edit: Ya, sourcepawn's compiler has a file named: amx.h

**Comment by xPaw** [comment]
That is true

**Comment by WildCard65** [comment]
@xPaw Is AMXX's string escape character different, I can't remember 100% for sure but I believe I read somewhere it's '^' instead of '\'?

**Comment by xPaw** [comment]
By default yes, but it's changeable via #pragma, iirc.

**Comment by WildCard65** [comment]
@xPaw @50Wliu The only thing that may be confusing for AMXX coders if this repo does adapt to support AMXX is the SM 1.7 syntax keywords(int, void, etc)

**Comment by WildCard65** [comment]
Is it alright if I drag @SmileYzn to this?

**Comment by winstliu** [comment]
Just dropping in here to say that I haven't forgotten about this; I've just been really busy lately with a different project.

**Comment by winstliu** [comment]
Ok.  If I do add support for `.sma`, one of two things will happen.
Scenario 1: I simply add `.sma` under the supported filetypes list, which will properly highlight `.sma` files, but their tokens will all still be `*.sp` (eg `constant.numeric.sp`).
Scenario 2: I add a different `.cson` file named `amxxpawn.cson` or something and copy/paste everything from `sourcepawn.cson` into it but find+replace `.sp`-->`.sma`, which isn't that much better than what @SmileYzn is doing right now.

Thoughts?

**Comment by WildCard65** [comment]
@50Wliu, if atom supports templates, y not make one for the common stuff
between amxx pawn and sourcepawn? If not, try to get that into atom then
work from there for SP and SMA

**Comment by xPaw** [comment]
I don't think `.sp` is such a big deal to be worried about.

**Comment by winstliu** [comment]
AMXX users will have to deal with `\` escape characters and new-style syntax tokenization for now.
